---
- hosts: webservers
  become: true
- tasks:
    - name: Install latest version of Apache
      apt: 
        name=apache2 
        update_cache=yes 
        state=latest
    - name: Start Apache server
      service:
        name: apache2
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
