---
- hosts: hosts
  tasks:
  - name: ansible create directory example
    file:
      path: /tmp/devops_directory
      state: directory
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
  ...
