- hosts: webservers
  tasks:
   - name: Ansible create directory and set permissions    
     file:
       path: /home/azureuser/    
        state: directory      
        mode: "u=rw,g=wx,o=rwx"    
   become: yes